// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_scrWallpaper = NULL;
lv_obj_t * ui_lblScreenClock = NULL;
lv_obj_t * ui_btnUnlockScreen = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_imgScreenLogo = NULL;
// event funtions
void ui_event_btnUnlockScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_scrMain_screen_init);
    }
}

void ui_event_Container2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_scrMain_screen_init);
    }
}

// build funtions

void ui_scrWallpaper_screen_init(void)
{
    ui_scrWallpaper = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrWallpaper, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrWallpaper, lv_color_hex(0x020202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrWallpaper, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblScreenClock = lv_label_create(ui_scrWallpaper);
    lv_obj_set_width(ui_lblScreenClock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblScreenClock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblScreenClock, -197);
    lv_obj_set_y(ui_lblScreenClock, -61);
    lv_obj_set_align(ui_lblScreenClock, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblScreenClock, "\n");
    lv_obj_set_style_text_color(ui_lblScreenClock, lv_color_hex(0x00AAF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblScreenClock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblScreenClock, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnUnlockScreen = lv_btn_create(ui_scrWallpaper);
    lv_obj_set_width(ui_btnUnlockScreen, 711);
    lv_obj_set_height(ui_btnUnlockScreen, 377);
    lv_obj_set_x(ui_btnUnlockScreen, -10);
    lv_obj_set_y(ui_btnUnlockScreen, 2);
    lv_obj_set_align(ui_btnUnlockScreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnUnlockScreen, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnUnlockScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnUnlockScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnUnlockScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnUnlockScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnUnlockScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_btnUnlockScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_btnUnlockScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnUnlockScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnUnlockScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_scrWallpaper);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 989);
    lv_obj_set_height(ui_Container2, 440);
    lv_obj_set_x(ui_Container2, -3);
    lv_obj_set_y(ui_Container2, -26);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgScreenLogo = lv_img_create(ui_scrWallpaper);
    lv_img_set_src(ui_imgScreenLogo, &ui_img_wallpaperlogo_png);
    lv_obj_set_width(ui_imgScreenLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgScreenLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgScreenLogo, -9);
    lv_obj_set_y(ui_imgScreenLogo, -31);
    lv_obj_set_align(ui_imgScreenLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgScreenLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgScreenLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_imgScreenLogo, 180);

    lv_obj_add_event_cb(ui_btnUnlockScreen, ui_event_btnUnlockScreen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container2, ui_event_Container2, LV_EVENT_ALL, NULL);

}

void ui_scrWallpaper_screen_destroy(void)
{
    if(ui_scrWallpaper) lv_obj_del(ui_scrWallpaper);

    // NULL screen variables
    ui_scrWallpaper = NULL;
    ui_lblScreenClock = NULL;
    ui_btnUnlockScreen = NULL;
    ui_Container2 = NULL;
    ui_imgScreenLogo = NULL;

}
