// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_scrSettings = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_lblHexnetTechnology5 = NULL;
lv_obj_t * ui_Button18 = NULL;
lv_obj_t * ui_lblLock5 = NULL;
lv_obj_t * ui_lblPanelSettingsB = NULL;
lv_obj_t * ui_lblThemeSettingsB = NULL;
lv_obj_t * ui_lblConnectionSettingsB = NULL;
lv_obj_t * ui_dbLanguage = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Image5 = NULL;
// event funtions
void ui_event_Button18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrPages, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_scrPages_screen_init);
    }
}

void ui_event_dbLanguage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        selectLanguagecallback(e);
    }
}

void ui_event_Image3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrPanelSettings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_scrPanelSettings_screen_init);
    }
}

void ui_event_Image4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrTheme, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_scrTheme_screen_init);
    }
}

void ui_event_Image5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrCalibration, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_scrCalibration_screen_init);
    }
}

// build funtions

void ui_scrSettings_screen_init(void)
{
    ui_scrSettings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel5 = lv_obj_create(ui_scrSettings);
    lv_obj_set_width(ui_Panel5, 1033);
    lv_obj_set_height(ui_Panel5, 42);
    lv_obj_set_x(ui_Panel5, 1);
    lv_obj_set_y(ui_Panel5, 281);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x006592), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblHexnetTechnology5 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_lblHexnetTechnology5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHexnetTechnology5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblHexnetTechnology5, 13);
    lv_obj_set_y(ui_lblHexnetTechnology5, 0);
    lv_obj_set_align(ui_lblHexnetTechnology5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblHexnetTechnology5, "HEXNET TECHNOLOGY");
    lv_obj_set_style_text_color(ui_lblHexnetTechnology5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblHexnetTechnology5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblHexnetTechnology5, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button18 = lv_btn_create(ui_scrSettings);
    lv_obj_set_width(ui_Button18, 136);
    lv_obj_set_height(ui_Button18, 113);
    lv_obj_set_x(ui_Button18, -445);
    lv_obj_set_y(ui_Button18, 247);
    lv_obj_set_align(ui_Button18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button18, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button18, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button18, lv_color_hex(0x00AAF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Button18, lv_color_hex(0x00B0FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Button18, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button18, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblLock5 = lv_label_create(ui_Button18);
    lv_obj_set_width(ui_lblLock5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblLock5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblLock5, -1);
    lv_obj_set_y(ui_lblLock5, 5);
    lv_obj_set_align(ui_lblLock5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLock5, "Back");
    lv_obj_set_style_text_color(ui_lblLock5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblLock5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblLock5, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblPanelSettingsB = lv_label_create(ui_scrSettings);
    lv_obj_set_width(ui_lblPanelSettingsB, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPanelSettingsB, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblPanelSettingsB, -366);
    lv_obj_set_y(ui_lblPanelSettingsB, 145);
    lv_obj_set_align(ui_lblPanelSettingsB, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblPanelSettingsB, "PANEL\nSETTINGS");
    lv_obj_set_style_text_font(ui_lblPanelSettingsB, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblThemeSettingsB = lv_label_create(ui_scrSettings);
    lv_obj_set_width(ui_lblThemeSettingsB, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblThemeSettingsB, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblThemeSettingsB, -12);
    lv_obj_set_y(ui_lblThemeSettingsB, 144);
    lv_obj_set_align(ui_lblThemeSettingsB, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblThemeSettingsB, "THEME\nSETTINGS");
    lv_obj_set_style_text_font(ui_lblThemeSettingsB, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblConnectionSettingsB = lv_label_create(ui_scrSettings);
    lv_obj_set_width(ui_lblConnectionSettingsB, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblConnectionSettingsB, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblConnectionSettingsB, 330);
    lv_obj_set_y(ui_lblConnectionSettingsB, 143);
    lv_obj_set_align(ui_lblConnectionSettingsB, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblConnectionSettingsB, "CONNECTION\nSETTINGS");
    lv_obj_set_style_text_font(ui_lblConnectionSettingsB, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dbLanguage = lv_dropdown_create(ui_scrSettings);
    lv_dropdown_set_options(ui_dbLanguage, "TURKCE\nENGLISH");
    lv_obj_set_width(ui_dbLanguage, 200);
    lv_obj_set_height(ui_dbLanguage, 50);
    lv_obj_set_x(ui_dbLanguage, 392);
    lv_obj_set_y(ui_dbLanguage, -260);
    lv_obj_set_align(ui_dbLanguage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dbLanguage, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_dbLanguage, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_dbLanguage), &lv_font_montserrat_20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_scrSettings);
    lv_img_set_src(ui_Image3, &ui_img_outcontrols_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, -358);
    lv_obj_set_y(ui_Image3, -44);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 400);
    lv_obj_set_style_border_color(ui_Image3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Image3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Image3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_scrSettings);
    lv_img_set_src(ui_Image4, &ui_img_theme_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, -17);
    lv_obj_set_y(ui_Image4, -37);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 400);

    ui_Image5 = lv_img_create(ui_scrSettings);
    lv_img_set_src(ui_Image5, &ui_img_connectioncontrol_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, 320);
    lv_obj_set_y(ui_Image5, -41);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image5, 400);

    lv_obj_add_event_cb(ui_Button18, ui_event_Button18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dbLanguage, ui_event_dbLanguage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image3, ui_event_Image3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image4, ui_event_Image4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image5, ui_event_Image5, LV_EVENT_ALL, NULL);

}

void ui_scrSettings_screen_destroy(void)
{
    if(ui_scrSettings) lv_obj_del(ui_scrSettings);

    // NULL screen variables
    ui_scrSettings = NULL;
    ui_Panel5 = NULL;
    ui_lblHexnetTechnology5 = NULL;
    ui_Button18 = NULL;
    ui_lblLock5 = NULL;
    ui_lblPanelSettingsB = NULL;
    ui_lblThemeSettingsB = NULL;
    ui_lblConnectionSettingsB = NULL;
    ui_dbLanguage = NULL;
    ui_Image3 = NULL;
    ui_Image4 = NULL;
    ui_Image5 = NULL;

}
