// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void arcTemizSuValueChanged(lv_event_t * e);
void btnTemperaturesCallbackFunc(lv_event_t * e);
void btnDimsCallbackFunc(lv_event_t * e);
void motorMoveBackwardPressed(lv_event_t * e);
void motorMoveBackwardReleased(lv_event_t * e);
void motorMoveForwardPressed(lv_event_t * e);
void motorMoveForwardReleased(lv_event_t * e);
void btnWatersCallbackFunc(lv_event_t * e);
void savePanelSettings(lv_event_t * e);
void btnReturnfromscrDimsandSensorstoscrMainCallback(lv_event_t * e);
void selectLanguagecallback(lv_event_t * e);
void enRGBTurnONFunc(lv_event_t * e);
void enRGBTurnOFFFunc(lv_event_t * e);
void applyRGBColor(lv_event_t * e);
void btnSaveThemeFunc(lv_event_t * e);
void btnThemeWhiteFunc(lv_event_t * e);
void btnBlackThemeFunc(lv_event_t * e);
void sendCanFrameRGB_R(lv_event_t * e);
void sendCanFrameRGB_G(lv_event_t * e);
void sendCanFrameRGB_B(lv_event_t * e);
void btnMenuCallback(lv_event_t * e);
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
