// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCRDIMSANDSENSORSANDWATERS_H
#define UI_SCRDIMSANDSENSORSANDWATERS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrDimsandSensorsandWaters
extern void ui_scrDimsandSensorsandWaters_screen_init(void);
extern void ui_scrDimsandSensorsandWaters_screen_destroy(void);
extern lv_obj_t * ui_scrDimsandSensorsandWaters;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_lblHexnetTechnology3;
extern void ui_event_Button21(lv_event_t * e);
extern lv_obj_t * ui_Button21;
extern lv_obj_t * ui_lblLock8;
extern void ui_event_slDim1(lv_event_t * e);
extern lv_obj_t * ui_slDim1;
extern void ui_event_slDim2(lv_event_t * e);
extern lv_obj_t * ui_slDim2;
extern void ui_event_slDim3(lv_event_t * e);
extern lv_obj_t * ui_slDim3;
extern void ui_event_slDim4(lv_event_t * e);
extern lv_obj_t * ui_slDim4;
extern lv_obj_t * ui_lblDim1;
extern lv_obj_t * ui_lblDim2;
extern lv_obj_t * ui_lblDim3;
extern lv_obj_t * ui_lblDim4;
extern lv_obj_t * ui_arcTemperature1;
extern lv_obj_t * ui_lblTemperature1;
extern lv_obj_t * ui_arcTemperature2;
extern lv_obj_t * ui_lblTemperature2;
extern lv_obj_t * ui_lblUnderArcTemperature1;
extern lv_obj_t * ui_lblUnderArcTemperature2;
extern lv_obj_t * ui_arcWater1;
extern lv_obj_t * ui_lblWater1;
extern lv_obj_t * ui_arcWater2;
extern lv_obj_t * ui_lblWater2;
extern lv_obj_t * ui_lblUnderArcWater1;
extern lv_obj_t * ui_lblUnderArcWater2;
extern lv_obj_t * ui_imgTemp1;
extern lv_obj_t * ui_imgTemp2;
extern lv_obj_t * ui_lblDimLevel1;
extern lv_obj_t * ui_lblDimLevel2;
extern lv_obj_t * ui_lblDimLevel3;
extern lv_obj_t * ui_lblDimLevel4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

