// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_scrMain_screen_init(void)
{
    ui_scrMain = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrMain, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_Image2, &ui_img_logo3_png);
    lv_obj_set_width(ui_Image2, 40);
    lv_obj_set_height(ui_Image2, 40);
    lv_obj_set_x(ui_Image2, -485);
    lv_obj_set_y(ui_Image2, -277);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_arcGrup1 = lv_arc_create(ui_scrMain);
    lv_obj_set_width(ui_arcGrup1, 80);
    lv_obj_set_height(ui_arcGrup1, 80);
    lv_obj_set_x(ui_arcGrup1, -451);
    lv_obj_set_y(ui_arcGrup1, 37);
    lv_obj_set_align(ui_arcGrup1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_arcGrup1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                      LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_value(ui_arcGrup1, 75);
    lv_obj_set_style_arc_color(ui_arcGrup1, lv_color_hex(0xD9D9D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcGrup1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arcGrup1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arcGrup1, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_arcGrup1, lv_color_hex(0x00AAF6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcGrup1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcGrup1, lv_color_hex(0x0EAEF6), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcGrup1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_arcGrup1, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_arcGrup1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lblGrup1Oran1 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lblGrup1Oran1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblGrup1Oran1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblGrup1Oran1, -447);
    lv_obj_set_y(ui_lblGrup1Oran1, 38);
    lv_obj_set_align(ui_lblGrup1Oran1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblGrup1Oran1, "%55");
    lv_obj_set_style_text_font(ui_lblGrup1Oran1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblGrup1 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lblGrup1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblGrup1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblGrup1, -453);
    lv_obj_set_y(ui_lblGrup1, 94);
    lv_obj_set_align(ui_lblGrup1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblGrup1, "Clean Water");

    ui_arcGrup2 = lv_arc_create(ui_scrMain);
    lv_obj_set_width(ui_arcGrup2, 80);
    lv_obj_set_height(ui_arcGrup2, 80);
    lv_obj_set_x(ui_arcGrup2, -360);
    lv_obj_set_y(ui_arcGrup2, 38);
    lv_obj_set_align(ui_arcGrup2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_arcGrup2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                      LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_value(ui_arcGrup2, 25);
    lv_obj_set_style_arc_width(ui_arcGrup2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arcGrup2, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_arcGrup2, lv_color_hex(0x00DE20), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcGrup2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcGrup2, lv_color_hex(0x0EAEF6), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcGrup2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_arcGrup2, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_arcGrup2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lblGrup1Oran2 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lblGrup1Oran2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblGrup1Oran2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblGrup1Oran2, -358);
    lv_obj_set_y(ui_lblGrup1Oran2, 34);
    lv_obj_set_align(ui_lblGrup1Oran2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblGrup1Oran2, "%20");
    lv_obj_set_style_text_font(ui_lblGrup1Oran2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblGrup2 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lblGrup2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblGrup2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblGrup2, -357);
    lv_obj_set_y(ui_lblGrup2, 93);
    lv_obj_set_align(ui_lblGrup2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblGrup2, "Dirty Water");

    ui_Panel6 = lv_obj_create(ui_scrMain);
    lv_obj_set_width(ui_Panel6, 1027);
    lv_obj_set_height(ui_Panel6, 42);
    lv_obj_set_x(ui_Panel6, 0);
    lv_obj_set_y(ui_Panel6, 282);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x006592), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblHexnetTechnology9 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_lblHexnetTechnology9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHexnetTechnology9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblHexnetTechnology9, 13);
    lv_obj_set_y(ui_lblHexnetTechnology9, 0);
    lv_obj_set_align(ui_lblHexnetTechnology9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblHexnetTechnology9, "HEXNET TECHNOLOGY");
    lv_obj_set_style_text_color(ui_lblHexnetTechnology9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblHexnetTechnology9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblHexnetTechnology9, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_scrMain);
    lv_obj_set_width(ui_Button1, 136);
    lv_obj_set_height(ui_Button1, 112);
    lv_obj_set_x(ui_Button1, -448);
    lv_obj_set_y(ui_Button1, 246);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x00AAF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Button1, lv_color_hex(0x00B0FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Button1, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblLock = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_lblLock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblLock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblLock, -3);
    lv_obj_set_y(ui_lblLock, -6);
    lv_obj_set_align(ui_lblLock, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLock, "Menu");
    lv_obj_set_style_text_color(ui_lblLock, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblLock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblLock, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_scrMain);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 1332);
    lv_obj_set_y(ui_Switch1, -198);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);


    ui_pnlGrupSicaklikResim1 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_pnlGrupSicaklikResim1, &ui_img_1542361832);
    lv_obj_set_width(ui_pnlGrupSicaklikResim1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pnlGrupSicaklikResim1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pnlGrupSicaklikResim1, -214);
    lv_obj_set_y(ui_pnlGrupSicaklikResim1, 93);
    lv_obj_set_align(ui_pnlGrupSicaklikResim1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pnlGrupSicaklikResim1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_pnlGrupSicaklikResim1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblPnlGrup1SicaklikDeger1 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lblPnlGrup1SicaklikDeger1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPnlGrup1SicaklikDeger1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblPnlGrup1SicaklikDeger1, -180);
    lv_obj_set_y(ui_lblPnlGrup1SicaklikDeger1, 92);
    lv_obj_set_align(ui_lblPnlGrup1SicaklikDeger1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblPnlGrup1SicaklikDeger1, "35 C");

    ui_lblPnlGrup1Sicaklik1 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lblPnlGrup1Sicaklik1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPnlGrup1Sicaklik1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblPnlGrup1Sicaklik1, -262);
    lv_obj_set_y(ui_lblPnlGrup1Sicaklik1, 92);
    lv_obj_set_align(ui_lblPnlGrup1Sicaklik1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblPnlGrup1Sicaklik1, "In. Temp");

    ui_lblPnlGrup1Sicaklik2 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lblPnlGrup1Sicaklik2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPnlGrup1Sicaklik2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblPnlGrup1Sicaklik2, -259);
    lv_obj_set_y(ui_lblPnlGrup1Sicaklik2, 41);
    lv_obj_set_align(ui_lblPnlGrup1Sicaklik2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblPnlGrup1Sicaklik2, "Ex. Temp");

    ui_lblPnlGrup1SicaklikDeger2 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lblPnlGrup1SicaklikDeger2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPnlGrup1SicaklikDeger2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblPnlGrup1SicaklikDeger2, -180);
    lv_obj_set_y(ui_lblPnlGrup1SicaklikDeger2, 41);
    lv_obj_set_align(ui_lblPnlGrup1SicaklikDeger2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblPnlGrup1SicaklikDeger2, "35 C");

    ui_pnlGrupSicaklikResim2 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_pnlGrupSicaklikResim2, &ui_img_1542361832);
    lv_obj_set_width(ui_pnlGrupSicaklikResim2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pnlGrupSicaklikResim2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pnlGrupSicaklikResim2, -213);
    lv_obj_set_y(ui_pnlGrupSicaklikResim2, 42);
    lv_obj_set_align(ui_pnlGrupSicaklikResim2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pnlGrupSicaklikResim2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_pnlGrupSicaklikResim2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pnlOutputs = lv_obj_create(ui_scrMain);
    lv_obj_set_width(ui_pnlOutputs, 619);
    lv_obj_set_height(ui_pnlOutputs, 490);
    lv_obj_set_x(ui_pnlOutputs, 184);
    lv_obj_set_y(ui_pnlOutputs, -2);
    lv_obj_set_align(ui_pnlOutputs, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnlOutputs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlOutputs, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlOutputs, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlOutputs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnlOutputs, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_pnlOutputs, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pnlOutputs, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_pnlOutputs, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_pnlOutputs, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_pnlOutputs, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_pnlOutputs, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgBluetoothConnected = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgBluetoothConnected, &ui_img_btconnected_png);
    lv_obj_set_width(ui_imgBluetoothConnected, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgBluetoothConnected, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgBluetoothConnected, 480);
    lv_obj_set_y(ui_imgBluetoothConnected, -274);
    lv_obj_set_align(ui_imgBluetoothConnected, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgBluetoothConnected, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgBluetoothConnected, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblVangoText = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lblVangoText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblVangoText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblVangoText, -408);
    lv_obj_set_y(ui_lblVangoText, -275);
    lv_obj_set_align(ui_lblVangoText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblVangoText, "VANGO");
    lv_obj_set_style_text_font(ui_lblVangoText, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgsconnected = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgsconnected, &ui_img_sconnected_png);
    lv_obj_set_width(ui_imgsconnected, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgsconnected, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgsconnected, 421);
    lv_obj_set_y(ui_imgsconnected, -275);
    lv_obj_set_align(ui_imgsconnected, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgsconnected, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgsconnected, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgsnotconnected = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgsnotconnected, &ui_img_snotconnected_png);
    lv_obj_set_width(ui_imgsnotconnected, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgsnotconnected, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgsnotconnected, 421);
    lv_obj_set_y(ui_imgsnotconnected, -275);
    lv_obj_set_align(ui_imgsnotconnected, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgsnotconnected, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgsnotconnected, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgBluetoothNotConnected = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgBluetoothNotConnected, &ui_img_btnotconnected_png);
    lv_obj_set_width(ui_imgBluetoothNotConnected, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgBluetoothNotConnected, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgBluetoothNotConnected, 481);
    lv_obj_set_y(ui_imgBluetoothNotConnected, -274);
    lv_obj_set_align(ui_imgBluetoothNotConnected, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgBluetoothNotConnected, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgBluetoothNotConnected, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgWForecast = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgWForecast, &ui_img_weatherforecast2_png);
    lv_obj_set_width(ui_imgWForecast, 32);
    lv_obj_set_height(ui_imgWForecast, 38);
    lv_obj_set_x(ui_imgWForecast, -287);
    lv_obj_set_y(ui_imgWForecast, -273);
    lv_obj_set_align(ui_imgWForecast, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgWForecast, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgWForecast, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblDateAndTime = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lblDateAndTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblDateAndTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblDateAndTime, 78);
    lv_obj_set_y(ui_lblDateAndTime, -271);
    lv_obj_set_align(ui_lblDateAndTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblDateAndTime, "Battery : 12.5V    Date : 2020-01-01    Time : 12:30");
    lv_obj_set_style_text_font(ui_lblDateAndTime, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlSensors = lv_obj_create(ui_scrMain);
    lv_obj_set_width(ui_pnlSensors, 350);
    lv_obj_set_height(ui_pnlSensors, 238);
    lv_obj_set_x(ui_pnlSensors, -315);
    lv_obj_set_y(ui_pnlSensors, -131);
    lv_obj_set_align(ui_pnlSensors, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnlSensors, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlSensors, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlSensors, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlSensors, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_pnlSensors, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pnlSensors, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_pnlSensors, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_pnlSensors, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_pnlSensors, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_pnlSensors, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblWeather = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lblWeather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblWeather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblWeather, -220);
    lv_obj_set_y(ui_lblWeather, -273);
    lv_obj_set_align(ui_lblWeather, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblWeather, "Dubai 36*C");
    lv_obj_set_style_text_font(ui_lblWeather, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlConnectionLost = lv_obj_create(ui_scrMain);
    lv_obj_set_width(ui_pnlConnectionLost, 545);
    lv_obj_set_height(ui_pnlConnectionLost, 125);
    lv_obj_set_x(ui_pnlConnectionLost, -14);
    lv_obj_set_y(ui_pnlConnectionLost, -29);
    lv_obj_set_align(ui_pnlConnectionLost, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pnlConnectionLost, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_pnlConnectionLost, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlConnectionLost, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlConnectionLost, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlConnectionLost, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlConnectionLost, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_pnlConnectionLost, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pnlConnectionLost, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_pnlConnectionLost, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_pnlConnectionLost, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_pnlConnectionLost, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_pnlConnectionLost, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_pnlConnectionLost);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -5);
    lv_obj_set_y(ui_Label1, -17);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "MODULE CONNECTION LOST!");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button10 = lv_btn_create(ui_pnlConnectionLost);
    lv_obj_set_width(ui_Button10, 145);
    lv_obj_set_height(ui_Button10, 58);
    lv_obj_set_x(ui_Button10, 0);
    lv_obj_set_y(ui_Button10, 26);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button10, lv_color_hex(0x005FAE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_pnlConnectionLost);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -2);
    lv_obj_set_y(ui_Label6, 25);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "CLOSE");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnRGBColor = lv_btn_create(ui_scrMain);
    lv_obj_set_width(ui_btnRGBColor, 100);
    lv_obj_set_height(ui_btnRGBColor, 43);
    lv_obj_set_x(ui_btnRGBColor, -427);
    lv_obj_set_y(ui_btnRGBColor, 141);
    lv_obj_set_align(ui_btnRGBColor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnRGBColor, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnRGBColor, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnRGBColor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnRGBColor, lv_color_hex(0x00AAF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRGBColor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_btnRGBColor);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -1);
    lv_obj_set_y(ui_Label7, 2);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "RGB");

    ui_Button6 = lv_btn_create(ui_scrMain);
    lv_obj_set_width(ui_Button6, 101);
    lv_obj_set_height(ui_Button6, 71);
    lv_obj_set_x(ui_Button6, -304);
    lv_obj_set_y(ui_Button6, 215);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button6, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button6, &ui_img_button_up_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button6, lv_color_hex(0x78CDFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_Button6, 20, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Button22 = lv_btn_create(ui_scrMain);
    lv_obj_set_width(ui_Button22, 101);
    lv_obj_set_height(ui_Button22, 71);
    lv_obj_set_x(ui_Button22, -200);
    lv_obj_set_y(ui_Button22, 216);
    lv_obj_set_align(ui_Button22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button22, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button22, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button22, &ui_img_button_down_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button22, lv_color_hex(0x78CDFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_Button22, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_Button22, 20, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_arcGrup1, ui_event_arcGrup1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arcGrup2, ui_event_arcGrup2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);

}
