// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_scrTheme = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_lblHexnetTechnology4 = NULL;
lv_obj_t * ui_Button14 = NULL;
lv_obj_t * ui_lblLock3 = NULL;
lv_obj_t * ui_btnBlackTheme = NULL;
lv_obj_t * ui_lblSelectTheme = NULL;
lv_obj_t * ui_lblSettingsB = NULL;
lv_obj_t * ui_rlrTime = NULL;
lv_obj_t * ui_swEnableWallpaper = NULL;
lv_obj_t * ui_lblWallpaper = NULL;
lv_obj_t * ui_btnWhiteTheme = NULL;
// event funtions
void ui_event_Button14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrSettings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_scrSettings_screen_init);
        btnSaveThemeFunc(e);
    }
}

void ui_event_btnBlackTheme(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        btnBlackThemeFunc(e);
    }
}

void ui_event_swEnableWallpaper(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_rlrTime, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_rlrTime, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_btnWhiteTheme(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        btnThemeWhiteFunc(e);
    }
}

// build funtions

void ui_scrTheme_screen_init(void)
{
    ui_scrTheme = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrTheme, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel4 = lv_obj_create(ui_scrTheme);
    lv_obj_set_width(ui_Panel4, 1023);
    lv_obj_set_height(ui_Panel4, 42);
    lv_obj_set_x(ui_Panel4, 2);
    lv_obj_set_y(ui_Panel4, 280);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x006592), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblHexnetTechnology4 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_lblHexnetTechnology4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHexnetTechnology4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblHexnetTechnology4, 13);
    lv_obj_set_y(ui_lblHexnetTechnology4, 0);
    lv_obj_set_align(ui_lblHexnetTechnology4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblHexnetTechnology4, "HEXNET TECHNOLOGY");
    lv_obj_set_style_text_color(ui_lblHexnetTechnology4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblHexnetTechnology4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblHexnetTechnology4, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button14 = lv_btn_create(ui_scrTheme);
    lv_obj_set_width(ui_Button14, 136);
    lv_obj_set_height(ui_Button14, 117);
    lv_obj_set_x(ui_Button14, -449);
    lv_obj_set_y(ui_Button14, 244);
    lv_obj_set_align(ui_Button14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button14, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button14, lv_color_hex(0x00AAF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Button14, lv_color_hex(0x00B0FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Button14, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button14, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblLock3 = lv_label_create(ui_Button14);
    lv_obj_set_width(ui_lblLock3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblLock3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblLock3, 1);
    lv_obj_set_y(ui_lblLock3, 0);
    lv_obj_set_align(ui_lblLock3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLock3, "Save");
    lv_obj_set_style_text_color(ui_lblLock3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblLock3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblLock3, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnBlackTheme = lv_btn_create(ui_scrTheme);
    lv_obj_set_width(ui_btnBlackTheme, 209);
    lv_obj_set_height(ui_btnBlackTheme, 210);
    lv_obj_set_x(ui_btnBlackTheme, 143);
    lv_obj_set_y(ui_btnBlackTheme, -177);
    lv_obj_set_align(ui_btnBlackTheme, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnBlackTheme, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnBlackTheme, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnBlackTheme, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnBlackTheme, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnBlackTheme, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnBlackTheme, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnBlackTheme, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnBlackTheme, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSelectTheme = lv_label_create(ui_scrTheme);
    lv_obj_set_width(ui_lblSelectTheme, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSelectTheme, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSelectTheme, -304);
    lv_obj_set_y(ui_lblSelectTheme, -187);
    lv_obj_set_align(ui_lblSelectTheme, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSelectTheme, "Select Theme:");
    lv_obj_set_style_text_font(ui_lblSelectTheme, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSettingsB = lv_label_create(ui_scrTheme);
    lv_obj_set_width(ui_lblSettingsB, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSettingsB, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSettingsB, -1778);
    lv_obj_set_y(ui_lblSettingsB, -185);
    lv_obj_set_align(ui_lblSettingsB, LV_ALIGN_CENTER);

    ui_rlrTime = lv_roller_create(ui_scrTheme);
    lv_roller_set_options(ui_rlrTime, "30 Seconds\n1 Minute\n2 Minutes\n5 Minutes\n10 Minutes", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_rlrTime, 615);
    lv_obj_set_height(ui_rlrTime, 142);
    lv_obj_set_x(ui_rlrTime, -8);
    lv_obj_set_y(ui_rlrTime, 135);
    lv_obj_set_align(ui_rlrTime, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rlrTime, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_rlrTime, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swEnableWallpaper = lv_switch_create(ui_scrTheme);
    lv_obj_set_width(ui_swEnableWallpaper, 214);
    lv_obj_set_height(ui_swEnableWallpaper, 94);
    lv_obj_set_x(ui_swEnableWallpaper, -2);
    lv_obj_set_y(ui_swEnableWallpaper, -8);
    lv_obj_set_align(ui_swEnableWallpaper, LV_ALIGN_CENTER);

    ui_lblWallpaper = lv_label_create(ui_scrTheme);
    lv_obj_set_width(ui_lblWallpaper, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblWallpaper, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblWallpaper, -272);
    lv_obj_set_y(ui_lblWallpaper, -5);
    lv_obj_set_align(ui_lblWallpaper, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblWallpaper, "Enable Wallpaper:");
    lv_obj_set_style_text_font(ui_lblWallpaper, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnWhiteTheme = lv_btn_create(ui_scrTheme);
    lv_obj_set_width(ui_btnWhiteTheme, 210);
    lv_obj_set_height(ui_btnWhiteTheme, 204);
    lv_obj_set_x(ui_btnWhiteTheme, -85);
    lv_obj_set_y(ui_btnWhiteTheme, -180);
    lv_obj_set_align(ui_btnWhiteTheme, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnWhiteTheme, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnWhiteTheme, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnWhiteTheme, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnWhiteTheme, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnWhiteTheme, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnWhiteTheme, lv_color_hex(0xCDCACD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnWhiteTheme, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnWhiteTheme, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button14, ui_event_Button14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnBlackTheme, ui_event_btnBlackTheme, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_swEnableWallpaper, ui_event_swEnableWallpaper, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnWhiteTheme, ui_event_btnWhiteTheme, LV_EVENT_ALL, NULL);

}

void ui_scrTheme_screen_destroy(void)
{
    if(ui_scrTheme) lv_obj_del(ui_scrTheme);

    // NULL screen variables
    ui_scrTheme = NULL;
    ui_Panel4 = NULL;
    ui_lblHexnetTechnology4 = NULL;
    ui_Button14 = NULL;
    ui_lblLock3 = NULL;
    ui_btnBlackTheme = NULL;
    ui_lblSelectTheme = NULL;
    ui_lblSettingsB = NULL;
    ui_rlrTime = NULL;
    ui_swEnableWallpaper = NULL;
    ui_lblWallpaper = NULL;
    ui_btnWhiteTheme = NULL;

}
